# -*- coding: utf-8 -*-
"""prepare_ground_truth.py: generate the reference/deformed image pair for a
known-ground-truth DVC accuracy check (stage 1 of 4; see
run_ground_truth_pipeline.py for the full chain: this script ->
preprocess.py -> run_dvc.py -> ground_truth/analyse_ground_truth.py).

--gt-ref-file PATH (default: assets/GT_z+0.01/ref.npy)
  reference image .npy file, shape (N, N, N), any dtype.

--gt-displacement-file PATH (default: assets/GT_z+0.01/U.npy)
  ground-truth displacement .npy file, shape (N+1, N+1, N+1, 3), float,
  channels-last (ux, uy, uz), in voxel units. Mutually exclusive with
  --tensile-strain; exactly one of the two must supply the displacement
  field (this one, by default, unless --tensile-strain is given).

  The displacement field must have exactly one more grid point per axis than
  the reference image: it is sampled at integer coordinates 0..N (N+1
  points), while the image's voxels sit at integer coordinates 0..N-1 (N
  points) -- i.e. the displacement grid extends one voxel further per axis,
  giving interpolation a margin so no image voxel ever needs extrapolation.
  For the bundled ground-truth datasets in assets/, N=65 (image) and
  N+1=66 (displacement).

--tensile-strain STRAIN replaces --gt-displacement-file with a synthetic
  uniaxial field u_x(x,y,z) = STRAIN * x, u_y = u_z = 0 (same
  (N+1,N+1,N+1,3) layout, sized from --gt-ref-file), so the rest of the
  pipeline is unchanged. Positive STRAIN is tension, negative is
  compression. Mutually exclusive with --gt-displacement-file.

Deformed image is generated by warping the reference with the ground-truth
displacement field via RegularGridInterpolator (trilinear,
bounds_error=False, fill_value=None):
  deformed(x) = ref(x - u_gt(x))

Output (--output-dir, default dvc_elastic_groundtruth/gt_input):
  ref.npy       reference image, original dtype, shape (N,N,N)
  deformed.npy  deformed image, float64, shape (N,N,N)
  u_gt_vox.npy  ground-truth displacement interpolated onto every reference
                image voxel, float64, shape (N,N,N,3) -- consumed by
                ground_truth/analyse_ground_truth.py so the GT field is
                interpolated from its native (N+1,N+1,N+1,3) grid exactly once.
  gt_meta.json  provenance (GT ref/displacement file or tensile-strain value, shapes)
"""

import argparse
import json
import os
import sys

import numpy as np
from scipy.interpolate import RegularGridInterpolator

# The elastic ground-truth dataset lives in the repo's assets/ directory
# (alongside the PA6GF30 CT pair), resolved relative to the current working
# directory -- matching DEFAULT_OUTPUT_DIR and the assets/ paths used in the
# README/TUTORIAL, i.e. the defaults assume the pipeline is run from the repo
# root.
GT_DIR = os.path.join(os.path.abspath('assets'), 'GT_z+0.01')
DEFAULT_GT_REF_FILE = os.path.join(GT_DIR, 'ref.npy')
DEFAULT_GT_DISPLACEMENT_FILE = os.path.join(GT_DIR, 'U.npy')
# Default output is relative to the current working directory (there's no
# meaningful "repo root" once this package is installed). This applies only
# when this stage is run standalone; run_ground_truth_pipeline.py always
# passes an explicit --output-dir (from its required --output-dir).
DEFAULT_OUTPUT_DIR = os.path.join(os.path.abspath('dvc_elastic_groundtruth'), 'gt_input')


def make_deformed_image(ref, u_gt_vox):
    """Create deformed image via backward warp: deformed(x) = ref(x - u(x)).

    ref      : (nx, ny, nz) float64 reference volume.
    u_gt_vox : (nx, ny, nz, 3) ground-truth displacement at every image voxel.
    """
    nx, ny, nz = ref.shape
    x_coords = np.arange(nx, dtype=float)
    y_coords = np.arange(ny, dtype=float)
    z_coords = np.arange(nz, dtype=float)

    interp_ref = RegularGridInterpolator(
        (x_coords, y_coords, z_coords), ref,
        method='linear', bounds_error=False, fill_value=None,
    )

    X, Y, Z = np.meshgrid(x_coords, y_coords, z_coords, indexing='ij')
    sample_pts = np.column_stack([
        (X - u_gt_vox[..., 0]).ravel(),
        (Y - u_gt_vox[..., 1]).ravel(),
        (Z - u_gt_vox[..., 2]).ravel(),
    ])
    return interp_ref(sample_pts).reshape(ref.shape)


def make_uniaxial_gt(n, strain):
    """Synthetic ground-truth: uniaxial tensile strain in x, u_y = u_z = 0.

    Matches the layout of a loaded --gt-displacement-file ground truth
    (n, n, n, 3) grid with integer coordinates 0..n-1, so it drops into the
    rest of the pipeline (image warp, GT comparison) unchanged.

    n      : grid points per axis (== reference image size + 1, see module
             docstring for the image/displacement dimension relationship).
    strain : du_x/dx, applied as u_x(x, y, z) = strain * x.
    """
    u = np.zeros((n, n, n, 3), dtype=np.float64)
    x_coords = np.arange(n, dtype=np.float64)
    u[..., 0] = strain * x_coords[:, None, None]
    return u


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument(
        '--gt-ref-file', type=str, default=DEFAULT_GT_REF_FILE, dest='gt_ref_file',
        help=f"Reference image .npy file, shape (N,N,N), any dtype "
             f"(default: {DEFAULT_GT_REF_FILE}).",
    )
    group = p.add_mutually_exclusive_group()
    group.add_argument(
        '--gt-displacement-file', type=str, default=DEFAULT_GT_DISPLACEMENT_FILE,
        dest='gt_displacement_file',
        help=f"Ground-truth displacement .npy file, shape (N+1,N+1,N+1,3) -- "
             f"see module docstring for the dimension relationship to "
             f"--gt-ref-file (default: {DEFAULT_GT_DISPLACEMENT_FILE}). "
             f"Mutually exclusive with --tensile-strain.",
    )
    group.add_argument(
        '--tensile-strain', type=float, default=None, dest='tensile_strain',
        help="Impose a synthetic uniaxial tensile strain du_x/dx (x direction "
             "only, u_y=u_z=0) instead of loading --gt-displacement-file. "
             "E.g. 0.01 for 1%% strain. Mutually exclusive with "
             "--gt-displacement-file.",
    )
    p.add_argument(
        '--output-dir', type=str, default=DEFAULT_OUTPUT_DIR, dest='output_dir',
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    output_dir = os.path.expanduser(args.output_dir)
    gt_ref_file = os.path.expanduser(args.gt_ref_file)
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 70)
    print("PREPARE GROUND-TRUTH IMAGE PAIR")
    print("=" * 70)

    # --- load inputs ---
    ref_raw = np.load(gt_ref_file)
    nx, ny, nz = ref_raw.shape
    assert nx == ny == nz, f"reference image must be cubic (N,N,N), got {ref_raw.shape}"

    if args.tensile_strain is not None:
        print(f"\nImposing synthetic uniaxial tensile strain: "
              f"du_x/dx = {args.tensile_strain} (x direction only, u_y=u_z=0)")
        u_gt = make_uniaxial_gt(nx + 1, args.tensile_strain)
        gt_source = {'type': 'tensile_strain', 'strain': args.tensile_strain}
    else:
        gt_displacement_file = os.path.expanduser(args.gt_displacement_file)
        u_gt = np.load(gt_displacement_file).astype(np.float64)
        expected_shape = (nx + 1, ny + 1, nz + 1)
        assert u_gt.shape[:3] == expected_shape and u_gt.shape[3:] == (3,), (
            f"ground-truth displacement field must have shape (N+1,N+1,N+1,3) "
            f"for an (N,N,N) reference image -- i.e. one more grid point per "
            f"axis than the image (displacement sampled at integer "
            f"coordinates 0..N, image voxels at 0..N-1). Got reference "
            f"{ref_raw.shape} (N={nx}) vs. displacement {u_gt.shape}, "
            f"expected {expected_shape + (3,)}."
        )
        gt_source = {'type': 'ct_displacement_field', 'file': gt_displacement_file}
    print(f"Reference: {ref_raw.shape} {ref_raw.dtype}  "
          f"min={ref_raw.min()}  max={ref_raw.max()}")
    print(f"GT displacement: {u_gt.shape} {u_gt.dtype}")
    for c, name in enumerate(['ux', 'uy', 'uz']):
        print(f"  GT {name}: min={u_gt[..., c].min():.4f}  max={u_gt[..., c].max():.4f}")

    ref = ref_raw.astype(np.float64)

    # --- interpolate GT displacement from its (N+1,N+1,N+1) grid to image (N,N,N) voxels ---
    # GT grid: N+1 uniformly spaced points per axis, integer coordinates 0..N.
    # Image voxels are at integer coordinates 0..N-1, fully inside the GT domain.
    gt_axis = np.arange(u_gt.shape[0], dtype=float)  # 0..N
    img_axis = np.arange(nx, dtype=float)             # 0..N-1
    X, Y, Z = np.meshgrid(img_axis, img_axis, img_axis, indexing='ij')
    img_pts = np.column_stack([X.ravel(), Y.ravel(), Z.ravel()])

    u_gt_vox = np.zeros((nx, ny, nz, 3), dtype=np.float64)
    for c in range(3):
        interp_u = RegularGridInterpolator(
            (gt_axis, gt_axis, gt_axis), u_gt[..., c],
            method='linear', bounds_error=False, fill_value=None,
        )
        u_gt_vox[..., c] = interp_u(img_pts).reshape(nx, ny, nz)

    print(f"\nGT displacement at image voxels (interpolated):")
    for c, name in enumerate(['ux', 'uy', 'uz']):
        print(f"  {name}: min={u_gt_vox[..., c].min():.4f}  max={u_gt_vox[..., c].max():.4f}")

    # --- generate deformed image ---
    deformed = make_deformed_image(ref, u_gt_vox)
    print(f"\nDeformed image: min={deformed.min():.2f}  max={deformed.max():.2f}")

    out_ref = os.path.join(output_dir, 'ref.npy')
    out_def = os.path.join(output_dir, 'deformed.npy')
    out_gt_vox = os.path.join(output_dir, 'u_gt_vox.npy')
    out_meta = os.path.join(output_dir, 'gt_meta.json')

    np.save(out_ref, ref.astype(ref_raw.dtype))
    np.save(out_def, deformed)
    np.save(out_gt_vox, u_gt_vox)
    with open(out_meta, 'w') as fh:
        json.dump({
            'gt_ref_file': gt_ref_file,
            'ground_truth_source': gt_source,
            'ref_shape': list(ref.shape),
            'ref_dtype': str(ref_raw.dtype),
        }, fh, indent=2)

    print(f"\nSaved {out_ref}  shape={ref.shape}  dtype={ref_raw.dtype}")
    print(f"Saved {out_def}  shape={deformed.shape}  dtype={deformed.dtype}")
    print(f"Saved {out_gt_vox}  shape={u_gt_vox.shape}  dtype={u_gt_vox.dtype}")
    print(f"Saved {out_meta}")
    print("\n✓ PREPARE GROUND-TRUTH COMPLETE")


if __name__ == "__main__":
    main()
